version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=abadatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/abadatabase
        SPRING_DATASOURCE_USERNAME: myuser
        SPRING_DATASOURCE_PASSWORD: secret
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

volumes:
  postgres_data: